### ISSUE TITLE
phoenix

### ISSUE THREAD

**Issue by AlexKim900628** [AlexKim900628/workwith#1]
aws

**Comment by the-phoenix** [comment]
Yes, sure. you can keep using it.

**Comment by the-phoenix** [comment]
Hey. Can you checkout how's login working? Thanks!

**Comment by AlexKim900628** [comment]
it has an error on login.vue
plz check this source code
tks

**Comment by AlexKim900628** [comment]
> @AlexKim900628 i've updated your commit. please check again. Thanks!

hey Sir. plz create a new gdoc and let me know it's addr. tks

**Comment by the-phoenix** [comment]
@AlexKim900628 I want to invite you to the doc. Whats your gmail address?

**Comment by the-phoenix** [comment]
@AlexKim900628 Please review
https://docs.google.com/document/d/1dJtf7Q0rWuAOHWIq_uxDqUC6q3QXOXtOHCdO8krSy4w/edit?usp=sharing

**Comment by AlexKim900628** [comment]
sth wrong on network so gdoc will not be possible for several days. I know u received yesterday. could u send it to below addr via p.pal?
cooperativedev@outlook.com

**Comment by the-phoenix** [comment]
Is it 0.77?

**Comment by AlexKim900628** [comment]
y

**Comment by the-phoenix** [comment]
recipient firstname/lastname and country or residence please?

**Comment by AlexKim900628** [comment]
can u do via p. oneer?

**Comment by the-phoenix** [comment]
i can't.
